spring:
  cloud:
    nacos:
      discovery:
        enabled: false
        # server-addr: ${NACOS_SERVER_ADDR}
        # namespace: ${NACOS_NAMESPACE}
        # username: ${NACOS_USERNAME}
        # password: ${NACOS_PASSWORD}
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
