server:
  port: 9092
spring:
  application:
    name: transfer-service
  config:
    import:
      - optional:file:./transfer_service/.env[.properties]
  profiles:
    active: dev
    # sentinel:
    #   transport:
    #     port: 8719
    #     dashboard: 192.168.31.134:8080
    #   http-method-specify: true

mybatis:
  mapper-locations: classpath:alisa/mapper/xml/*.xml
